### ISSUE TITLE
Fix schedule creation

### ISSUE THREAD

**Issue by djadczak956** [worcestertechnicalhighschool/ratatoskr#197]
For some reason, schedule creation does not produce a schedule. Is it because of a student account or because something broke?

**Comment by seamussmith** [comment]
Schedule creation depends on the Google Calendar API, as shown in the [on_schedule_create](https://github.com/worcestertechnicalhighschool/ratatoskr/blob/master/ratatoskr/app/models.py#L78) model signal. My best guess is that Google may have invalidated the API key due to underuse and you might have to create a new one. 

Some logs or exception messages, if any appear, may also be helpful.

**Comment by seamussmith** [comment]
also good luck maintaining ratatoskr

**Comment by seamussmith** [comment]
I ran the project on a local machine and I just found out through debugging that the auto_lock_after field is not being set by the form. This field is required by the ScheduleCreationForm, and when this field isn't set, the form fails validation and returns the page with the list of errors, but the template does not use the list of errors. 

For more information you can try setting a breakpoint at [line 89 of views.py](https://github.com/worcestertechnicalhighschool/ratatoskr/blob/master/ratatoskr/app/views.py#L89)

**Comment by djadczak956** [comment]
Alright, thanks for the help. I'll check that out.

**Comment by djadczak956** [comment]
@seamussmith on [line 26 of create_schedule.html](https://github.com/worcestertechnicalhighschool/ratatoskr/blob/master/ratatoskr/app/templates/app/pages/create_schedule.html) I got the schedule creation working by adding `value="on"` inside the tag. I also noticed that this was removed in a previous pull request, so I was wondering if there was a reason for removing this from the tag?

**Comment by djadczak956** [comment]
bruh
I'll go through with that change then.
